[window]
opacity = 0.8
blur = true

[font]
normal = { family = "FiraCode Nerd Font", style="Regular" }
bold = { family = "FiraCode Nerd Font", style="Bold" }
italic = { family = "FiraCode Nerd Font", style="Light" }
bold_italic = { family = "FiraCode Nerd Font", style="Bold Medium" }

[general]
import = [
    "themes/vscode.toml",
    "alacritty.local.toml",
]
